#!/bin/bash
# ehv5 app
# Generated by dx-app-wizard.
#
# Basic execution pattern: Your app will run on a single machine from
# beginning to end.
#
# Your job's input variables (if any) will be loaded as environment
# variables before this script runs.  Any array inputs will be loaded
# as bash arrays.
#
# Any code outside of main() (or any entry point you may add) is
# ALWAYS executed, followed by running the entry point itself.
#
# See https://documentation.dnanexus.com/developer for tutorials on how
# to modify this file.

main() {

    # The following line(s) use the dx command-line tool to download your file
    # inputs to the local file system using variable names for the filenames. To
    # recover the original filenames, you can use the output of "dx describe
    # "$variable" --name".
    dx download "$reference" -o reference
    dx download "$variant_catalog" -o variant_catalog

    length=${#reads[@]}
    for i in $(seq 0 $(($length - 1)))
    do
        readspath=${reads[$i]} 
        prefix=${output_prefix[$i]}
        echo "Processing Cram file: '$readspath'"
        dx download "$readspath" -o mapped_reads

        dx download "${readspath}".crai -o mapped_reads.crai
    
        ExpansionHunter \
        --reads mapped_reads --reference reference --variant-catalog variant_catalog --output-prefix $prefix \
        --sex $sex --threads $threads --analysis-mode $analysis_mode
        rm mapped_reads*
        sambamba sort -o "$prefix"_sorted.bam "$prefix"_realigned.bam
        sambamba index "$prefix"_sorted.bam
        bgzip -c "$prefix".vcf > "$prefix".temp.vcf.gz # compress vcf
        echo $prefix > sample.id
        bcftools reheader -s sample.id "$prefix".temp.vcf.gz -o "$prefix".vcf.gz #reheader sample with EID
        bcftools index -t "$prefix".vcf.gz
        bcftools query -f '%VARID %CHROM %POS\n' "$prefix".vcf.gz > variants.txt
        jq -r '.[] | select(.LocusStructure | gsub("[^\\(]";"") | length >= 2) | .LocusId' variant_catalog > multi_str.txt
        Rscript add_extra_tags.r --sample "$prefix" --variants variants.txt --multi-strs multi_str.txt
        # The following line(s) use the dx command-line tool to upload your file
        # outputs after you have created them on the local file system.  It assumes
        # that you have used the output field name for the filename for each output,
        # but you can change that behavior to suit your needs.  Run "dx upload -h"
        # to see more options to set metadata.

        vcf=$(dx upload "$prefix".annot.vcf.gz --brief --path "$output_folder"/"$prefix".annot.vcf.gz -p)
        index_vcf=$(dx upload "$prefix".annot.vcf.gz.tbi --brief --path "$output_folder"/"$prefix".annot.vcf.gz.tbi -p)
        
        # The following line(s) use the utility dx-jobutil-add-output to format and
        # add output variables to your job's output as appropriate for the output
        # class.  Run "dx-jobutil-add-output -h" for more information on what it
        # does.

        dx-jobutil-add-output vcf "$vcf" --array
        dx-jobutil-add-output index_vcf "$index_vcf" --array
        rm "$prefix"*
    done
}
